export const formatAzureRegion = (regionCode: string): string => {
  const mappings: Record<string, string> = {
    attatlanta1: "AT&T Atlanta",
    attdallas1: "AT&T Dallas",
    attdetroit1: "AT&T Detroit",
    attnewyork1: "AT&T New York",
    australiacentral: "Australia Central",
    australiacentral2: "Australia Central 2",
    australiaeast: "Australia East",
    australiasoutheast: "Australia Southeast",
    austriaeast: "Austria East",
    beigiuncentral: "Belgium Central",
    belgiumcentral: "Belgium Central",
    brazilsouth: "Brazil South",
    brazilsoutheast: "Brazil Southeast",
    canadacentral: "Canada Central",
    canadaeast: "Canada East",
    centralindia: "Central India",
    centralus: "Central US",
    chilecentral: "Chile Central",
    denmarkeast: "Denmark East",
    eastasia: "East Asia",
    eastus: "East US",
    eastus2: "East US 2",
    francecentral: "France Central",
    francesouth: "France South",
    germanynorth: "Germany North",
    germanywestcentral: "Germany West Central",
    global: "Global",
    indonesiacentral: "Indonesia Central",
    israelcentral: "Israel Central",
    israelnorthwest: "Israel Northwest",
    italynorth: "Italy North",
    japaneast: "Japan East",
    japanwest: "Japan West",
    jioindiacentral: "Jio India Central",
    jioindiawest: "Jio India West",
    koreacentral: "Korea Central",
    koreasouth: "Korea South",
    malaysiawest: "Malaysia West",
    mexicocentral: "Mexico Central",
    newzealandnorth: "New Zealand North",
    northcentralus: "North Central US",
    northeurope: "North Europe",
    norwayeast: "Norway East",
    norwaywest: "Norway West",
    polandcentral: "Poland Central",
    portland: "Portland",
    qatarcentral: "Qatar Central",
    sgxsingapore1: "SGX Singapore 1",
    southafricanorth: "South Africa North",
    southafricawest: "South Africa West",
    southcentralus: "South Central US",
    southcentralus2: "South Central US 2",
    southeastasia: "Southeast Asia",
    southeastus: "Southeast US",
    southindia: "South India",
    southwestus: "Southwest US",
    spaincentral: "Spain Central",
    swedencentral: "Sweden Central",
    swedensouth: "Sweden South",
    switzerlandnorth: "Switzerland North",
    switzerlandwest: "Switzerland West",
    uaecentral: "UAE Central",
    uaenorth: "UAE North",
    uksouth: "UK South",
    ukwest: "UK West",
    usgov: "US Gov",
    usgovarizona: "US Gov Arizona",
    usgoviowa: "US Gov Iowa",
    usgovtexas: "US Gov Texas",
    usgovvirginia: "US Gov Virginia",
    westcentralus: "West Central US",
    westeurope: "West Europe",
    westindia: "West India",
    westus: "West US",
    westus2: "West US 2",
    westus3: "West US 3",
  };

  return (
    mappings[regionCode] ||
    regionCode
      .split(/(?=[A-Z])|(?<=[a-z])(?=[0-9])/)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ")
  );
};

export const formatAWSRegion = (regionCode: string): string => {
  const mappings: Record<string, string> = {
    argentinabuenosaires: "Buenos Aires, Argentina",
    africacapetown: "Cape Town, South Africa",
    asiapacifichongkong: "Hong Kong",
    asiapacifichyderabad: "Hyderabad, India",
    asiapacificjakarta: "Jakarta, Indonesia",
    "asiapacifickddi-osaka": "Osaka, Japan (KDDI)",
    "asiapacifickddi-tokyo": "Tokyo, Japan (KDDI)",
    asiapacificmalaysia: "Malaysia",
    asiapacificmelbourne: "Melbourne, Australia",
    asiapacificmumbai: "Mumbai, India",
    asiapacificnewzealand: "New Zealand",
    asiapacificosaka: "Osaka, Japan",
    asiapacificseoul: "Seoul, South Korea",
    asiapacificsingapore: "Singapore",
    "asiapacificskt-daejeon": "Daejeon, South Korea (SKT)",
    "asiapacificskt-seoul": "Seoul, South Korea (SKT)",
    asiapacificsydney: "Sydney, Australia",
    asiapacifictaipei: "Taipei, Taiwan",
    asiapacificthailand: "Thailand",
    asiapacifictokyo: "Tokyo, Japan",
    australiaperth: "Perth, Australia",
    "awsgovcloudus-east": "AWS GovCloud (US-East)",
    "awsgovcloudus-west": "AWS GovCloud (US-West)",
    "canadabell-toronto": "Toronto, Canada (Bell)",
    canadacentral: "Canada Central",
    canadawestcalgary: "Calgary, Canada",
    chilesantiago: "Santiago, Chile",
    chinaautocloudbeijing: "Beijing, China (Auto Cloud)",
    chinabeijing: "Beijing, China",
    chinaningxia: "Ningxia, China",
    denmarkcopenhagen: "Copenhagen, Denmark",
    eufrankfurt: "Frankfurt, Germany",
    euireland: "Ireland",
    eulondon: "London, UK",
    eumilan: "Milan, Italy",
    euparis: "Paris, France",
    "europebritishtelecom-manchester": "Manchester, UK (BT)",
    europespain: "Spain",
    "europevodafone-berlin": "Berlin, Germany (Vodafone)",
    "europevodafone-dortmund": "Dortmund, Germany (Vodafone)",
    "europevodafone-london": "London, UK (Vodafone)",
    "europevodafone-manchester": "Manchester, UK (Vodafone)",
    "europevodafone-munich": "Munich, Germany (Vodafone)",
    europezurich: "Zurich, Switzerland",
    eustockholm: "Stockholm, Sweden",
    finlandhelsinki: "Helsinki, Finland",
    germanyhamburg: "Hamburg, Germany",
    indiadelhi: "Delhi, India",
    indiakolkata: "Kolkata, India",
    israeltelaviv: "Tel Aviv, Israel",
    mexicocentral: "Mexico Central",
    mexicoqueretaro: "Queretaro, Mexico",
    middleeastbahrain: "Bahrain",
    middleeastuae: "UAE",
    moroccocasablanca: "Casablanca, Morocco",
    newzealandauckland: "Auckland, New Zealand",
    nigerialagos: "Lagos, Nigeria",
    omanmuscat: "Muscat, Oman",
    perulima: "Lima, Peru",
    philippinesmanila: "Manila, Philippines",
    polandwarsaw: "Warsaw, Poland",
    senegaldakar: "Dakar, Senegal",
    southamericasaopaulo: "São Paulo, Brazil",
    taiwantaipei: "Taipei, Taiwan",
    thailandbangkok: "Bangkok, Thailand",
    useastatlanta: "Atlanta, US East",
    useastboston: "Boston, US East",
    useastchicago: "Chicago, US East",
    useastdallas: "Dallas, US East",
    useasthouston: "Houston, US East",
    useastkansascity2: "Kansas City, US East",
    useastlenexa: "Lenexa, US East",
    useastmiami: "Miami, US East",
    useastminneapolis: "Minneapolis, US East",
    "useastn.virginia": "N. Virginia, US East",
    useastnewyorkcity: "New York City, US East",
    useastohio: "Ohio, US East",
    useastphiladelphia: "Philadelphia, US East",
    "useastverizon-atlanta": "Atlanta, US East (Verizon)",
    "useastverizon-boston": "Boston, US East (Verizon)",
    "useastverizon-charlotte": "Charlotte, US East (Verizon)",
    "useastverizon-chicago": "Chicago, US East (Verizon)",
    "useastverizon-dallas": "Dallas, US East (Verizon)",
    "useastverizon-detroit": "Detroit, US East (Verizon)",
    "useastverizon-houston": "Houston, US East (Verizon)",
    "useastverizon-miami": "Miami, US East (Verizon)",
    "useastverizon-minneapolis": "Minneapolis, US East (Verizon)",
    "useastverizon-nashville": "Nashville, US East (Verizon)",
    "useastverizon-newyork": "New York, US East (Verizon)",
    "useastverizon-tampa": "Tampa, US East (Verizon)",
    "useastverizon-washingtondc": "Washington DC, US East (Verizon)",
    uswestdenver: "Denver, US West",
    uswesthonolulu: "Honolulu, US West",
    uswestlasvegas: "Las Vegas, US West",
    uswestlosangeles: "Los Angeles, US West",
    "uswestn.california": "N. California, US West",
    uswestoregon: "Oregon, US West",
    uswestphoenix: "Phoenix, US West",
    uswestportland: "Portland, US West",
    uswestseattle: "Seattle, US West",
    "uswestverizon-denver": "Denver, US West (Verizon)",
    "uswestverizon-lasvegas": "Las Vegas, US West (Verizon)",
    "uswestverizon-losangeles": "Los Angeles, US West (Verizon)",
    "uswestverizon-phoenix": "Phoenix, US West (Verizon)",
    "uswestverizon-sanfranciscobayarea":
      "San Francisco Bay Area, US West (Verizon)",
    "uswestverizon-seattle": "Seattle, US West (Verizon)",
  };

  return (
    mappings[regionCode] ||
    regionCode
      .replace(/([a-z])([A-Z])/g, "$1 $2")
      .split(/[ -]/)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ")
  );
};

export const getRegionDisplayName = (
  regionCode: string,
  provider: "aws" | "azure" | "gcp"
): string => {
  if (!regionCode || regionCode.trim() === "") return "No Region";

  if (provider === "azure") {
    return formatAzureRegion(regionCode);
  } else if (provider === "aws") {
    return formatAWSRegion(regionCode);
  }
  return regionCode
    .split(/(?=[A-Z])|(?<=[a-z])(?=[0-9])/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};
