/** Stable selectors for spotlight + designer hint pips */
export const AMG_DESIGNER = {
  versions: "amg-designer-versions",
  versionMove: "amg-designer-version-move",
  versionRename: "amg-designer-version-rename",
  versionDelete: "amg-designer-version-delete",
  toolbarDownloads: "amg-designer-toolbar-downloads",
  returnToChat: "amg-designer-return-to-chat",
  viewSuggestions: "amg-designer-view-suggestions",
  suggestionModal: "amg-designer-suggestion-modal",
  suggestionModalToolbar: "amg-designer-suggestion-modal-toolbar",
  suggestionFirstCard: "amg-designer-suggestion-card-0",
  suggestionFirstPreview: "amg-designer-suggestion-preview-0",
  suggestionModalFooter: "amg-designer-suggestion-modal-footer",
  legend: "amg-designer-legend",
  legendHelp: "amg-designer-legend-help",
  simulator: "amg-designer-simulator",
  simulationModal: "amg-designer-simulation-modal",
  simulationVersionSelect: "amg-designer-simulation-version-select",
  simulationModalFooter: "amg-designer-simulation-modal-footer",
  layout: "amg-designer-layout",
  stats: "amg-designer-stats",
  editGraph: "amg-designer-edit-graph",
  generate: "amg-designer-generate",
  reset: "amg-designer-reset",
  fullscreen: "amg-designer-fullscreen",
  newDesignerSwitch: "amg-designer-new-designer",
  toolbox: "amg-designer-toolbox",
  editToolboxSearch: "amg-designer-edit-toolbox-search",
  editToolboxNodes: "amg-designer-edit-toolbox-nodes",
  editToolboxAntiPatterns: "amg-designer-edit-toolbox-antipatterns",
  canvas: "amg-designer-canvas",
  details: "amg-designer-details",
  detailsSelection: "amg-designer-details-selection",
  detailsAntiPattern: "amg-designer-details-antipattern",
  detailsExport: "amg-designer-details-export",
  connectionTools: "amg-designer-connection-tools",
  versionCompare: "amg-designer-version-compare",
} as const;

export type AmgDesignerAnchor = (typeof AMG_DESIGNER)[keyof typeof AMG_DESIGNER];
